'use strict';

module.exports = {
	0: {status: ''}, /* loading,error,abort */
	/* SUCCESS */
	200: {status: 'Ok'},
	201: {status: 'Created'},
	202: {status: 'Accepted'},
	203: {status: 'Non-Authoritative Information'},
	204: {status: 'No Contant'},
	205: {status: 'Reset Contant'},
	206: {status: 'Partial Content'},
	207: {status: 'Multi-status'},
	208: {status: 'Already Reported'},
	226: {status: 'IM Used'},
	/* REDIRECT */
	/* CLIENT ERROR */
	400: {status: 'Bad Request'},
	401: {status: 'Unauthorized'},
	402: {status: 'Payment Required'},
	403: {status: 'Forbidden'},
	404: {status: 'Not Found'},
	405: {status: 'Method Not Allowed'},
	406: {status: 'Not Acceptable'},
	407: {status: 'Proxy Authentication Required'},
	408: {status: 'Request Time-out'},
	409: {status: 'Conflict'},
	410: {status: 'Gone'},
	411: {status: 'Length Required'},
	412: {status: 'Precondition Failed'},
	413: {status: 'Payload Too Large'},
	414: {status: 'URI Too Long'},
	415: {status: 'Unsupported Media Type'},
	416: {status: 'Range Not Satisfiable'},
	417: {status: 'Expectation Failed'},
	418: {status: 'I\'m a teapot'},
	422: {status: 'Misdirected Request'},
	423: {status: 'Unprocessable Entity'},
	424: {status: 'Locked'},
	425: {status: 'Failed Dependency'},
	426: {status: 'Upgrade Required'},
	428: {status: 'Precondition Required'},
	429: {status: 'Too Many Requests'},
	431: {status: 'Request Header Fields Too Large'},
	440: {status: 'Login Time-out'},
	444: {status: 'No Response'},
	449: {status: 'Retry With'},
	// 450: ''},
	451: {status: 'Unavailable For Legal Reasons'},
	495: {status: 'SSL Certificate Error'},
	496: {status: 'SSL Certificate Required'},
	497: {status: 'HTTP Request Sent to HTTPS Port'},
	499: {status: 'Client Closed Request'},
	/* SERVER ERROR */
	500: {status: 'Internal Server Error'},
	501: {status: 'Not Implemented'},
	502: {status: 'Bad Gateway'},
	503: {status: 'Service Unavailable'},
	504: {status: 'Gateway Time-out'},
	505: {status: 'HTTP Version Not Supported'},
	506: {status: 'Variant Also Negotiates'},
	507: {status: 'Insufficient Storage'},
	508: {status: 'Loop Detected'},
	// 509: ''},
	510: {status: 'Not Extended'},
	511: {status: 'Network Authentication Required'},
	// 598: },
	// 599: },
	520: {status: 'Unknown Error'},
	521: {status: 'Web Server Is Down'},
	522: {status: 'Connection Timed Out'},
	523: {status: 'Origin Is Unreachable'},
	524: {status: 'A Timeout Occurred'},
	525: {status: 'SSL Handshake Failed'},
	526: {status: 'Invalid SSL Certificate'},
	527: {status: 'Railgun Error'},
	'default': {status: 'Default Handler'},
	'timeout': {status: 'Timeout Handler'},
	'abort': {status: 'Abort Handler'}
};
